#!/bin/bash
#clear

extn=$1
#To find the extension of file
extn=${extn##*.}

if [ $extn != 'java' ]
    then
echo -e '\n-------Compiling' $*'---------->'
#Check for C/C++ file 
if [ $extn == 'c' ]
    then 
        gcc $*
else
        g++ -std=c++11 $*
fi

status=$?
if [ $status -eq 0 ]
    then
        #clear
        echo -e '\n<---------Compilation Succesfull--------->'
        echo -e '<----------Running Code-------------------'
        echo -e '\n'
        ./a.out
        echo -e '\n'
        echo -e '----------End of Code running------------>\n'
fi

else
        echo -e '\n<---------Compiling & Running Code--------->'
#        echo -e '\n'
        java $*
        status=$?
        if [ $status -eq 0 ]
            then
                echo -e '\n'
                echo -e '----------End of Code running------------>\n'
        fi
fi

