#!/bin/bash

#To get help
if [ $# -eq 0 ] || [ $# -ne 0 ]
      then
      	   if [ "$1" == "-h" ] || [ "$1" == "--help" ] || [ "$1" == "-help" ] || [ "$1" == "--h" ] || [ $# -eq 0 ]
	    	then
			echo -e "\nCommand usage : Cvim file_name.extension "
            echo -e "\tThis command use to create .cpp/.c/.h/.java files with some pre-populate text in it "
			echo -e "\tFor normal editing a file use --> 'Cvim file_name'"
			echo -e "\tUse -sh To create new xyz_file.sh(bash_script) file"
			echo -e "\tTry and run 'Cvim hello.cpp' "
            echo -e "\n"
			exit
			fi
fi

#Check for second argument to create file ( C/C++ ) with extension ( .c/.cpp/.h ) specifiy by second argument
#****************

	user=($USER)
	user="$(echo "$user" | sed 's/.*/\u&/')"
        ti=$(date)
        extn=$1
        extn=${extn##*.}
	if [ -f "$1" ]
	then 
		vim $1
	# for creating bash script

	elif [ ! -z $2 ] && [ $2 == '-sh' ] && [ ! -f "$1" ] && [ ! -x "$1" ] 
	then
		touch $1
		chmod +x $1
		echo "#!/bin/bash" >> $1
                echo -e "\n#*******************************************************\n#\t  File name : $1" >> $1
                echo -e '#\tAuthor name :' >> $1 $user >> $1
                echo -e '#\t       Date :' >> $1 $ti  >> $1 
                echo -e '#********************************************************' >> $1
		vim $1
    #Check argument to create .c extension file
   elif [ $extn == 'c' ] && [ ! -f "$1" ] 
            then
		touch $1
		echo -e '/*******************************************************\n\t  File name : '$1 > $1
		echo -e '\tAuthor name :' >> $1 $user >> $1
		echo -e '\t       Date :' >> $1 $ti  >> $1
		echo -e '********************************************************/' >> $1
		echo -e '\n#include <stdio.h>' >> $1
		echo -e '#define endl printf("\\n")' >> $1
		echo -e '\nint main ( )\n{\n\treturn 0;\n}' >> $1
		vim $1
    #echo $1.h  ##For Testing only

    #Check argument to create .cpp extension file
   elif [ $extn == 'cpp' ]  && [ ! -f "$1" ]
            then
		touch $1
                echo -e '/*******************************************************\n\t  File name : '$1 > $1 
                echo -e '\tAuthor name :' >> $1 $user >> $1 
                echo -e '\t       Date :' >> $1 $ti  >> $1 
                echo -e '********************************************************/' >> $1
                echo -e '\n#include <iostream>' >> $1
                echo -e 'using namespace std ;' >> $1
                echo -e '\nint main ( )\n{\n\treturn 0;\n}' >> $1
                vim $1
    #echo $1.h  ##For Testing only

    #Check argument to create .h extension file
    elif [ $extn == 'h' ] && [ ! -f "$1" ] 
            then 
		touch $1
                echo -e '/*******************************************************\n\t  File name : '$1 > $1
                echo -e '\tAuthor name :' >> $1 $user >> $1
                echo -e '\t       Date :' >> $1 $ti  >> $1 
                echo -e '********************************************************/' >> $1
                echo -e '\n#endif' >> $1
                vim $1
    #echo $1  ##For Testing only
    
    #Check argument to create .cpp extension file
    elif [ $extn == 'java' ]  && [ ! -f "$1" ]
            then
	    	touch $1
                class=$1
			    class=${class%.*}
                echo -e '/*******************************************************\n\t  File name : '$1 > $1
                echo -e '\tAuthor name :' >> $1 $user >> $1 
                echo -e '\t       Date :' >> $1 $ti  >> $1
                echo -e '********************************************************/' >> $1
                echo -e '\nimport java.util.*;' >> $1
                echo -e 'public class' $class  >> $1
		echo -e '{\n\tpublic static void main(String[] args)\n\t{\n\t\tSystem.out.println("<---------------Running--------------->");\n\t}\n}' >> $1
                vim $1
#If the second argument is not supplied then open make file with name specifiy by $1 
    else
            vim $1
    fi
#****************
